apiVersion: apps/v1
kind: Deployment
metadata:
  name: cap-plan-creator
  namespace: default
  labels:
    app: cap-plan-creator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cap-plan-creator
  template:
    metadata:
      labels:
        app: cap-plan-creator
    spec:
      containers:
      - name: cap-plan-creator
        image: cap-plan-creator:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "8000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: output-storage
          mountPath: /app/data/output
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: output-storage
        persistentVolumeClaim:
          claimName: cap-plan-output-pvc 