apiVersion: v1
kind: Service
metadata:
  name: cap-plan-creator-service
  namespace: default
  labels:
    app: cap-plan-creator
spec:
  selector:
    app: cap-plan-creator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
  type: ClusterIP